.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. unbreakablecoin_qt test_unbreakablecoin_qt
clean: FORCE
	$(MAKE) -C .. unbreakablecoin_qt_clean test_unbreakablecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_unbreakablecoin_qt_check
unbreakablecoin-qt unbreakablecoin-qt.exe: FORCE
	 $(MAKE) -C .. unbreakablecoin_qt
